POST http://localhost:8081/register

{
    "username": "user1",
    "password": "123"
}

###

POST http://localhost:8081/login

{
    "username": "user1",
    "password": "123"
}

###

POST http://localhost:8081/refresh

{
    "refreshToken": "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjM5Mjc5MzIsImlhdCI6MTcyMzgxOTkzMiwiaXNzIjoiYXV0aC1zZXJ2aWNlIiwic3ViIjoiMSIsInR5cGUiOiJyZWZyZXNoIn0.8gY8dJLqqjA8wP7veGolXrQNQJPp26lxTgq3TXkxlMrO4itrqtbE0hZedE1Oq9btJIXBCCLtZUSgucTzZOljBQ"
}

###

GET http://localhost:8081/build
